### ISSUE TITLE
User granule downloads are NOT being saved / retained in the HiTIDE OPS UI

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide-ui#45]
Details here:

https://jira.jpl.nasa.gov/browse/PODAAC-5720

**Comment by jamesfwood** [comment]
@jbyrne6 put in specific test case for David.  Thanks!

**Comment by davidcolemanjpl** [comment]
This is NOT an issue in  UAT env (4.17.2-RC.9)


NOTE:
This issue is only an issue in HiTIDE OPS (v4.17.1)
...if/when deployed to OPS env, I will validate at this time 


related Console error - currently happens in OPS env only
![Image](https://github.com/podaac/hitide-ui/assets/57456095/f8d8fd4b-2d64-47a0-86e2-cc289ae9edfc

**Comment by jamesfwood** [comment]
@davidcolemanjpl please test again in HiTIDE UAT.  Hopefully it is fixed now. 
Thanks!

**Comment by davidcolemanjpl** [comment]
This is NOT (or was never) an issue in HiTIDE **UAT** env ( v4.17.2-rc.10)

NOTE:
This issue is only an issue in HiTIDE **OPS** env (v4.17.1).  Granule downloads are still NOT being saved / retained in UI. 


related Console error - currently happens in HiTIDE OPS env only:
![OPS-console-error-1](https://github.com/user-attachments/assets/37711192-2e0f-4336-b10e-839d91c7d089)

**Comment by jamesfwood** [comment]
@davidcolemanjpl this is now deployed to OPS.  Please test again. 
Thanks!

**Comment by davidcolemanjpl** [comment]
**HiTIDE (OPS) v4.17.2**
HiTIDE Profile v4.10.1
l2ss-py:2.11.0
concise:0.9.0
Chrome v128.0.6613.120 (Official Build) (arm64)


This issue appears to be currently resolved in HiTIDE OPS. 

User granule downloads are now being saved as expected in the HiTIDE UI after a refresh and / or after the user logs out and back into the HiTIDE app.
