### ISSUE TITLE
HiTIDE UI - UAT - 500 (Internal Server Error) and 400 (Bad Request) errors display in UI console

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide-ui#70]
JIRA Link:

https://jira.jpl.nasa.gov/browse/PODAAC-6247

**Comment by jamesfwood** [comment]
@jbyrne6 Make sure Hitide works in SIT also

**Comment by davidcolemanjpl** [comment]
**HiTIDE-UI UAT** v4.17.2-rc.10:
HiTIDE -Profile v4.11.0-4-a02b64f9f23d21815d1a76debe0d5d98a163bd65

User can Trigger errors by selecting icon for MERGED_TP_J1_OSTM_OST_CYCLES_V52, and then selecting info icon for other collections in UAT UI:

![400-500errors-UAT-081224](https://github.com/user-attachments/assets/2de28887-c50b-4c9e-8176-8a62f613cda0)

**Comment by jamesfwood** [comment]
@davidcolemanjpl please test again in HiTIDE UAT.  Hopefully it is fixed now. 
Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE-UI UAT v4.17.2-rc.10
HiTIDE -Profile v4.10.1-rc.16
Chrome browser v127.0.6533.100 (Official Build) (arm64)


500 (Internal Server Error) and 400 (Bad Request) errors are still displaying in UI console:


![UATerrors-1](https://github.com/user-attachments/assets/d3388c0e-7180-4769-900a-b583d0e7508e)
![UAT errors2](https://github.com/user-attachments/assets/d264e777-a1b8-47f7-9d20-b1d9659f15d7)



note:
User can Trigger 400/500 errors by selecting icon for MERGED_TP_J1_OSTM_OST_CYCLES_V52, and then selecting the info icon for other collections in the UAT UI

**Comment by jbyrne6** [comment]
### Conversation related to adding cmr feature to specify temporal facets foor granules
Jimmy Byrne
  Aug 2nd at 2:16 PM
Hi, I was wondering how I can specify temporal facets for granules in a graphql cmr query?  I see that I can include facets for collections but am not seeing it for granules. I am trying to convert this cmr call to graphql
[https://cmr.earthdata.nasa.gov:443/search/granules.json?include_facets=v2&page_size=0&collection_concept_id=C2075141524-POCLOUD&temporal[]=2007-03-27T00:00:00Z,2021-12-01T23:59:59Z&temporal_facet[0][year]=2007](https://cmr.earthdata.nasa.gov/search/granules.json?include_facets=v2&page_size=0&collection_concept_id=C2075141524-POCLOUD&temporal[]=2007-03-27T00:00:00Z,2021-12-01T23:59:59Z&temporal_facet[0][year]=2007)
Thanks for your help! (edited) 
4 replies

  [Aug 6th at 9:18 AM](https://jpl.slack.com/archives/C2LRKMDEV/p1722961136373359?thread_ts=1722633381.608389&cid=C2LRKMDEV)
It does not look like we currently support facets on the granule search for the temporal piece we can pass something like this as a POST request body to the https://graphql.earthdata.nasa.gov/api endpoint I’ll investigate at why that is and come back; since it is supported by CMR (edited) 

Eudoro Olivares Raniolo
 | Example without facets
 
query ($params: GranulesInput) {
  granules(params: $params) {
    items {
      conceptId
    }
Click to expand inline (15 lines)




Jimmy Byrne
  [Aug 6th at 9:40 AM](https://jpl.slack.com/archives/C2LRKMDEV/p1722962429400019?thread_ts=1722633381.608389&cid=C2LRKMDEV)
Ok got it, thank you for your help! Having this in graphql would help speed up our loading time significantly for HiTIDE UI.


Jimmy Byrne
  Aug 8th at 10:47 AM
[@eudoro.a.olivaresraniolo](https://jpl.slack.com/team/U03LE5MSRHU)
, I was wondering if you know how long it would take to support facets on granule search? I am not currently able to get the month counts work correctly when I do a single rest cmr call with all the applicable years. The initial issue was that it was doing one call per year that the collection was active and I wanted to reduce it to one call to get the granule counts per year, month, and day. Thank you for your help! (edited) 


Jimmy Byrne
  Aug 29th at 3:04 PM
Hi 
[@eudoro.a.olivaresraniolo](https://jpl.slack.com/team/U03LE5MSRHU)
, I would like to just re-up my question and see if there is a graphql update in the works anytime soon relating to adding facets on granule search?

**Comment by jbyrne6** [comment]
I sent a direct message to Eudoro today (9/23/24) to remind him of the question so am waiting for that response.
